Repository FairwindsOps/goldilocks, pull requests merged in 2022-10, with the labels that each got.

#528 Make namespace filter links unique
  pkg/dashboard/templates/namespace.gohtml
Labels: hacktoberfest-accepted

#530 Make summary elements more accessible
  pkg/dashboard/assets/css/main.css
  pkg/dashboard/templates/api_token.gohtml
  pkg/dashboard/templates/container.gohtml
  pkg/dashboard/templates/cost_settings.gohtml
  pkg/dashboard/templates/email.gohtml
  pkg/dashboard/templates/namespace.gohtml
Labels: hacktoberfest

#531 Make headings only contain heading content
  pkg/dashboard/assets/css/main.css
  pkg/dashboard/templates/container.gohtml
Labels: hacktoberfest-accepted

#527 update dependecies
  .circleci/config.yml
  .goreleaser.yml
  go.mod
  go.sum
Labels: hacktoberfest-accepted

#546 Fixed duplicated requests
  pkg/dashboard/assets/js/self-identification.js
  pkg/dashboard/templates/head.gohtml
Labels: bug

#544 Improve navigation accessibility and usability
  pkg/dashboard/assets/css/main.css
  pkg/dashboard/assets/js/filter.js
  pkg/dashboard/assets/js/main.js
  pkg/dashboard/assets/js/utilities.js
  pkg/dashboard/helpers/helpers.go
  pkg/dashboard/router.go
  pkg/dashboard/templates.go
  pkg/dashboard/templates/dashboard.gohtml
  pkg/dashboard/templates/filter.gohtml
  pkg/dashboard/templates/head.gohtml
  pkg/dashboard/templates/namespace.gohtml
  pkg/dashboard/templates/namespace_list.gohtml
  pkg/dashboard/templates/navbar.gohtml
  pkg/dashboard/templates/navigation.gohtml
  pkg/summary/constants_test.go
  pkg/summary/summary.go
Labels: hacktoberfest-accepted
